import type { Locale } from "./i18n";

type Section={title:string;body:string};
type InfoCopy={
  nav:{help:string;support:string;status:string;terms:string;privacy:string;copyright:string;dmca:string};
  legal:{effective:string;questions:string};
  about:{kicker:string;title:string;summary:string;values:Array<{title:string;body:string}>};
  help:{kicker:string;title:string;summary:string;topics:Section[];still:string;stillBody:string;contact:string};
  status:{kicker:string;title:string;summary:string;platform:string;attention:string;operational:string;affected:string;services:string[];history:string;none:string;loading:string;updated:string};
  support:{kicker:string;title:string;summary:string;contact:string;how:string;setup:string;topic:string;subject:string;happened:string;create:string;created:string;failed:string;historyFailed:string;requests:string;empty:string;reply:string;replySent:string;replyFailed:string;topics:string[]};
  terms:{kicker:string;title:string;summary:string;sections:Section[]};
  privacy:{kicker:string;title:string;summary:string;sections:Section[]};
  copyright:{kicker:string;title:string;summary:string;sections:Section[];action:string};
  takedown:{kicker:string;title:string;summary:string;sections:Section[];form:string;fields:{name:string;email:string;organization:string;work:string;urls:string;urlPlaceholder:string;goodFaith:string;accuracy:string;signature:string;submit:string;received:string;keep:string;failed:string}};
};

const en:InfoCopy={
  nav:{help:"Help center",support:"Contact support",status:"Service status",terms:"Terms",privacy:"Privacy",copyright:"Copyright",dmca:"DMCA"},
  legal:{effective:"Effective",questions:"Questions about these policies?"},
  about:{kicker:"ABOUT ANIVERSE",title:"Stories beyond the stars.",summary:"AniVerse is a creator-first home for original and rights-cleared animation, dependable playback, and respectful communities.",values:[{title:"Creator owned",body:"Publishing controls, teams, analytics, rights workflows, and transparent support."},{title:"Viewer centered",body:"Accessible playback, personal libraries, privacy controls, and watch parties."},{title:"Trust by design",body:"Moderation evidence, appeals, consent records, secure media, and operational transparency."}]},
  help:{kicker:"HELP CENTER",title:"Answers without the wait.",summary:"Browse common account, playback, creator, and safety topics.",topics:[{title:"Accounts and privacy",body:"Manage sessions, visibility, exports, backups, consent, and deletion."},{title:"Watching anime",body:"Use quality, captions, audio, chapters, intro skipping, PiP, fullscreen, and shortcuts."},{title:"Creator Studio",body:"Apply, invite a team, upload media, schedule releases, and review analytics."},{title:"Community safety",body:"Block accounts, report content, follow decisions, and submit appeals."},{title:"Watch parties",body:"Invite participants, manage permissions, reconnect, and synchronize playback."},{title:"Payments",body:"Understand tips, payment processing, refunds, and payout eligibility."}],still:"Still need help?",stillBody:"Create a tracked request and continue the conversation from your account.",contact:"Contact support"},
  status:{kicker:"LIVE OPERATIONS",title:"AniVerse service status",summary:"Current availability and recent incident updates across the platform.",platform:"PLATFORM STATUS",attention:"Some systems need attention",operational:"All systems operational",affected:"Affected",services:["Web app","Authentication","Playback","Creator Studio","Community","Notifications"],history:"Incident history",none:"No published incidents.",loading:"Loading status…",updated:"Updated"},
  support:{kicker:"ANIVERSE SUPPORT",title:"We’ll help you get back to the story.",summary:"Tracked requests keep account, playback, creator, billing, and safety conversations in one place.",contact:"CONTACT SUPPORT",how:"How can we help?",setup:"Connect AniVerse to Supabase and sign in to create tracked support requests.",topic:"Topic",subject:"Subject",happened:"What happened?",create:"Create support request",created:"Support request created.",failed:"Support request could not be created.",historyFailed:"Support history could not be loaded.",requests:"Your requests",empty:"No support requests yet.",reply:"Add a reply",replySent:"Reply sent.",replyFailed:"Reply could not be sent.",topics:["Account","Playback","Creator","Billing","Safety","Other"]},
  terms:{kicker:"SERVICE AGREEMENT",title:"Terms of Service",summary:"The rules that keep AniVerse safe for viewers, creators, and rights holders.",sections:[{title:"1. Your account",body:"Provide accurate information, protect your credentials, and meet the minimum legal age where you live."},{title:"2. The service",body:"AniVerse provides discovery, community, publishing, and streaming tools under a personal, limited, revocable license."},{title:"3. Creator content",body:"Creators retain ownership and grant the rights needed to host, encode, stream, promote, and moderate selected work."},{title:"4. Community conduct",body:"Do not harass, threaten, spam, evade enforcement, expose private information, or upload unlawful material."},{title:"5. Payments",body:"Payments use approved providers. Fees, taxes, refunds, chargebacks, and payouts follow checkout and provider rules."},{title:"6. Enforcement",body:"AniVerse may remove content, restrict features, issue strikes, or suspend access, with notice and appeals where appropriate."},{title:"7. Liability",body:"The service is provided as available. Rights and liability that cannot legally be excluded remain unaffected."},{title:"8. Changes and contact",body:"Material changes receive a new effective date and appropriate notice. Contact legal@aniverse.example."}]},
  privacy:{kicker:"YOUR DATA",title:"Privacy Policy",summary:"What AniVerse collects, why it is used, and the controls available to you.",sections:[{title:"Information we collect",body:"We process account, profile, library, creator, community, support, payment-reference, device, consent, and security information."},{title:"How we use information",body:"We provide and secure the service, synchronize libraries, deliver opted-in personalization and notifications, moderate abuse, and comply with law."},{title:"Legal bases",body:"Processing relies on contract, consent, legitimate interests, and legal obligations as applicable."},{title:"Sharing and processors",body:"Approved hosting, authentication, video, email, payment, monitoring, and push providers receive only necessary data. We do not sell personal information."},{title:"Retention and security",body:"Records are kept only as needed. AniVerse uses access controls, encryption, backups, audit records, and service-role isolation."},{title:"Your choices and rights",body:"Control visibility, analytics, notifications, sessions, exports, backups, and deletion from your account."},{title:"International use and children",body:"Cross-border processing uses appropriate safeguards. AniVerse is not directed to children unable to consent locally."}]},
  copyright:{kicker:"CREATOR RIGHTS",title:"Copyright Notice",summary:"AniVerse supports original work and responds to complete rights-holder notices.",sections:[{title:"Ownership",body:"AniVerse materials and creator works remain protected by their respective intellectual-property rights."},{title:"Permitted use",body:"Viewing does not transfer ownership or permit copying, redistribution, circumvention, or derivative works."},{title:"Rights-holder notices",body:"Submit a complete notice identifying the protected work, exact location, contact details, declarations, and signature."},{title:"Counter-notices and repeat infringement",body:"Affected creators may respond. AniVerse may remove material and restrict repeat infringers while preserving evidence."}],action:"Submit a DMCA notice"},
  takedown:{kicker:"RIGHTS-HOLDER REQUEST",title:"DMCA takedown notice",summary:"Use this form only for copyright claims. Use in-product reporting for abuse, privacy, and community issues.",sections:[{title:"Before submitting",body:"Identify each protected work and provide every exact AniVerse URL. The notice may be shared with the affected creator."},{title:"What happens next",body:"AniVerse preserves evidence, checks required elements, may restrict material, and supports valid counter-notices."}],form:"Legal notice form",fields:{name:"Full legal name",email:"Email address",organization:"Organization (optional)",work:"Describe the copyrighted work",urls:"Exact AniVerse URL(s)",urlPlaceholder:"One full URL per line",goodFaith:"I believe in good faith that the disputed use is not authorized.",accuracy:"I confirm this notice is accurate and I am authorized to act for the rights owner.",signature:"Electronic signature",submit:"Submit notice",received:"Notice received",keep:"Keep this reference for follow-up or supporting evidence.",failed:"Notice could not be submitted."}}
};

const ja:InfoCopy={
  nav:{help:"ヘルプセンター",support:"サポートに連絡",status:"稼働状況",terms:"利用規約",privacy:"プライバシー",copyright:"著作権",dmca:"DMCA"},
  legal:{effective:"発効日",questions:"ポリシーに関するご質問"},
  about:{kicker:"ANIVERSEについて",title:"星を越える物語。",summary:"AniVerseは、オリジナル作品と権利処理済みアニメーションのための、クリエイター中心の配信コミュニティです。",values:[{title:"クリエイターの権利",body:"公開管理、チーム権限、分析、権利対応、透明なサポートを提供します。"},{title:"視聴者を中心に",body:"アクセシブルな再生、ライブラリ、プライバシー設定、ウォッチパーティーを提供します。"},{title:"信頼できる設計",body:"証拠に基づくモデレーション、異議申立て、同意記録、安全なメディア、稼働状況を提供します。"}]},
  help:{kicker:"ヘルプセンター",title:"待たずに答えを見つける。",summary:"アカウント、再生、クリエイター、安全性に関するよくある質問です。",topics:[{title:"アカウントとプライバシー",body:"セッション、公開範囲、エクスポート、バックアップ、同意、削除を管理します。"},{title:"アニメを視聴する",body:"画質、字幕、音声、チャプター、イントロスキップ、PiP、全画面、ショートカットを利用できます。"},{title:"クリエイタースタジオ",body:"申請、チーム招待、アップロード、公開予約、分析を管理します。"},{title:"コミュニティの安全",body:"ブロック、報告、審査結果、異議申立てを管理します。"},{title:"ウォッチパーティー",body:"参加者の招待、権限、再接続、同期再生を管理します。"},{title:"支払い",body:"投げ銭、決済、返金、受取資格について確認できます。"}],still:"解決しませんか？",stillBody:"追跡可能なサポート依頼を作成し、アカウントから会話を続けられます。",contact:"サポートに連絡"},
  status:{kicker:"リアルタイム運用",title:"AniVerse 稼働状況",summary:"プラットフォーム全体の現在の稼働状況と障害情報です。",platform:"プラットフォーム状況",attention:"一部のシステムに問題があります",operational:"すべてのシステムは正常です",affected:"影響あり",services:["ウェブアプリ","認証","再生","クリエイタースタジオ","コミュニティ","通知"],history:"障害履歴",none:"公開中の障害情報はありません。",loading:"状況を読み込み中…",updated:"更新"},
  support:{kicker:"ANIVERSEサポート",title:"物語に戻れるようお手伝いします。",summary:"アカウント、再生、クリエイター、請求、安全性の問い合わせを一か所で追跡できます。",contact:"サポートに連絡",how:"どのような問題ですか？",setup:"Supabaseに接続してサインインすると、追跡可能な依頼を作成できます。",topic:"トピック",subject:"件名",happened:"発生した内容",create:"サポート依頼を作成",created:"サポート依頼を作成しました。",failed:"サポート依頼を作成できませんでした。",historyFailed:"サポート履歴を読み込めませんでした。",requests:"あなたの依頼",empty:"サポート依頼はまだありません。",reply:"返信を追加",replySent:"返信を送信しました。",replyFailed:"返信を送信できませんでした。",topics:["アカウント","再生","クリエイター","請求","安全性","その他"]},
  terms:{kicker:"サービス契約",title:"利用規約",summary:"視聴者、クリエイター、権利者が安全に利用するための規則です。",sections:[{title:"1. アカウント",body:"正確な情報を提供し、認証情報を保護し、居住地域の最低年齢要件を満たしてください。"},{title:"2. サービス",body:"AniVerseは、発見、コミュニティ、公開、配信機能を個人的かつ取消可能なライセンスで提供します。"},{title:"3. クリエイター作品",body:"クリエイターは所有権を保持し、選択した作品の保存、変換、配信、宣伝、審査に必要な権利を許諾します。"},{title:"4. コミュニティ行動",body:"嫌がらせ、脅迫、スパム、処分回避、個人情報の公開、違法な素材の投稿は禁止です。"},{title:"5. 支払い",body:"承認済み事業者が決済します。手数料、税、返金、チャージバック、受取は表示された規則に従います。"},{title:"6. 執行",body:"必要に応じてコンテンツ削除、機能制限、ストライク、利用停止を行い、適切な場合は通知と異議申立てを提供します。"},{title:"7. 責任",body:"サービスは利用可能な状態で提供されます。法律上排除できない権利と責任は維持されます。"},{title:"8. 変更と連絡",body:"重要な変更には新しい発効日と適切な通知を付けます。legal@aniverse.exampleへご連絡ください。"}]},
  privacy:{kicker:"あなたのデータ",title:"プライバシーポリシー",summary:"収集する情報、利用目的、利用者が管理できる設定を説明します。",sections:[{title:"収集する情報",body:"アカウント、プロフィール、ライブラリ、作品、コミュニティ、サポート、決済参照、端末、同意、セキュリティ情報を処理します。"},{title:"利用目的",body:"サービス提供と保護、同期、選択したパーソナライズと通知、不正対策、法令遵守に使用します。"},{title:"法的根拠",body:"地域に応じ、契約、同意、正当な利益、法的義務を根拠に処理します。"},{title:"共有と処理事業者",body:"ホスティング、認証、動画、メール、決済、監視、プッシュ通知の承認済み事業者に必要な情報のみ共有します。個人情報は販売しません。"},{title:"保存と安全",body:"必要な期間のみ保存し、アクセス制御、暗号化、バックアップ、監査、サービスロール分離を使用します。"},{title:"選択と権利",body:"公開範囲、分析、通知、セッション、エクスポート、バックアップ、削除をアカウントで管理できます。"},{title:"国際利用と子ども",body:"国際処理には適切な保護措置を使用します。地域で同意できない子どもを対象としていません。"}]},
  copyright:{kicker:"クリエイターの権利",title:"著作権表示",summary:"AniVerseはオリジナル作品を尊重し、完全な権利者通知に対応します。",sections:[{title:"所有権",body:"AniVerseの素材とクリエイター作品は、それぞれの知的財産権で保護されます。"},{title:"許可される利用",body:"視聴によって所有権は移転せず、複製、再配布、回避、二次利用は許可されません。"},{title:"権利者通知",body:"保護作品、正確な場所、連絡先、宣誓、署名を含む完全な通知を提出してください。"},{title:"反論通知と反復侵害",body:"影響を受けたクリエイターは回答できます。証拠を保存しながら削除や反復侵害者の制限を行う場合があります。"}],action:"DMCA通知を提出"},
  takedown:{kicker:"権利者からの申請",title:"DMCA削除通知",summary:"著作権の申立て専用です。迷惑行為、プライバシー、コミュニティ問題はアプリ内報告をご利用ください。",sections:[{title:"提出前に",body:"保護対象の作品とAniVerse上の正確なURLをすべて記載してください。通知は対象クリエイターと共有される場合があります。"},{title:"提出後の流れ",body:"証拠と必要事項を確認し、素材を制限する場合があります。有効な反論通知にも対応します。"}],form:"法的通知フォーム",fields:{name:"法的氏名",email:"メールアドレス",organization:"組織名（任意）",work:"著作物の説明",urls:"AniVerseの正確なURL",urlPlaceholder:"1行に完全なURLを1つ",goodFaith:"問題の利用が許可されていないと誠実に信じます。",accuracy:"通知が正確で、権利者を代理する権限があることを確認します。",signature:"電子署名",submit:"通知を提出",received:"通知を受領しました",keep:"追加資料や問い合わせのため参照番号を保管してください。",failed:"通知を提出できませんでした。"}}
};

export const legalSupportMessages:Record<Locale,InfoCopy>={en,ja};
export type LegalSupportCopy=InfoCopy;
