"use client";
import{useCallback,useEffect,useState}from"react";import{Bell,Heart,LoaderCircle,MessageCircle,Plus,Send,UserPlus}from"lucide-react";import{initialCommunityState,useLocalDemoState,type CommunityState}from"@/lib/local-demo";import{isSupabaseConfigured}from"@/lib/supabase/config";
export function CommunityFeed(){const[community,setCommunity]=useLocalDemoState("aniverse.community",initialCommunityState);const[body,setBody]=useState("");const[replies,setReplies]=useState<Record<string,string>>({});const[busy,setBusy]=useState(false);const[error,setError]=useState("");const cloud=isSupabaseConfigured();const followed=community.followedCreators.includes("Lumen Works");
const load=useCallback(async()=>{if(!cloud)return;setBusy(true);const response=await fetch("/api/v1/community",{cache:"no-store"});const data=await response.json().catch(()=>({}))as{posts?:CommunityState["posts"];notifications?:CommunityState["notifications"];followedFeatured?:boolean;error?:string};if(response.ok)setCommunity({posts:data.posts??[],notifications:data.notifications??[],followedCreators:data.followedFeatured?["Lumen Works"]:[]});else setError(data.error??"Community could not be loaded.");setBusy(false)},[cloud,setCommunity]);useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
async function action(payload:object){const response=await fetch("/api/v1/community",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});if(!response.ok){const data=await response.json().catch(()=>({}))as{error?:string};setError(data.error??"Community action could not be saved.");return false}return true}
async function publish(event:React.FormEvent){event.preventDefault();const value=body.trim();if(!value)return;if(cloud){setBusy(true);if(await action({type:"post",body:value}))await load();setBusy(false)}else setCommunity(current=>({...current,posts:[{id:crypto.randomUUID(),author:"You",title:"Community post",body:value,likes:0,liked:false,replies:[]},...current.posts]}));setBody("")}
async function toggleFollow(){const next=!followed;if(cloud&&!await action({type:"follow-featured",followed:next}))return;setCommunity(current=>({...current,followedCreators:next?["Lumen Works"]:[]}))}
async function like(id:string){const post=community.posts.find(item=>item.id===id);if(!post)return;const liked=!post.liked;if(cloud&&!await action({type:"like",postId:id,liked}))return;setCommunity(current=>({...current,posts:current.posts.map(item=>item.id===id?{...item,liked,likes:item.likes+(liked?1:-1)}:item)}))}
async function reply(id:string){const value=replies[id]?.trim();if(!value)return;if(cloud&&!await action({type:"reply",postId:id,body:value}))return;setCommunity(current=>({...current,posts:current.posts.map(item=>item.id===id?{...item,replies:[...item.replies,value]}:item)}));setReplies(current=>({...current,[id]:""}))}
async function readAll(){if(cloud&&!await action({type:"read-notifications"}))return;setCommunity(current=>({...current,notifications:current.notifications.map(item=>({...item,read:true}))}))}
return <main className="community-page"><header><div><p>ANIVERSE COMMUNITY</p><h1>Stories are better together</h1><span>Discuss episodes, follow creators, and celebrate independent animation.</span></div><button disabled={busy} onClick={()=>void toggleFollow()}><UserPlus/>{followed?"Following Lumen Works":"Follow Lumen Works"}</button></header>{error&&<p className="form-error" role="alert">{error}</p>}<div className="community-grid"><section><form className="post-composer" onSubmit={event=>void publish(event)}><span>DL</span><textarea aria-label="Create community post" value={body} onChange={event=>setBody(event.target.value)} placeholder="Share a thought with the community..."/><button disabled={busy} aria-label="Publish post">{busy?<LoaderCircle className="spin"/>:<Send/>}</button></form><div className="feed-list">{community.posts.map(post=><article key={post.id}><header><span>{post.author.slice(0,1)}</span><div><b>{post.author}</b><small>{post.title}</small></div></header><p>{post.body}</p><div className="post-actions"><button className={post.liked?"active":""} onClick={()=>void like(post.id)}><Heart fill={post.liked?"currentColor":"none"}/>{post.likes}</button><button><MessageCircle/>{post.replies.length}</button></div>{post.replies.map((item,index)=><blockquote key={`${post.id}-${index}`}>{item}</blockquote>)}<form onSubmit={event=>{event.preventDefault();void reply(post.id)}}><input aria-label={`Reply to ${post.author}`} value={replies[post.id]??""} onChange={event=>setReplies(current=>({...current,[post.id]:event.target.value}))} placeholder="Write a reply..."/><button><Plus/></button></form></article>)}</div></section><aside><div className="notification-head"><Bell/><div><p>ACTIVITY</p><h2>Notifications</h2></div><button onClick={()=>void readAll()}>Mark all read</button></div>{community.notifications.map(item=><article className={item.read?"":"unread"} key={item.id}><b>{item.title}</b><p>{item.body}</p></article>)}</aside></div></main>}
