"use client";
import { useEffect,useState } from "react";
import { BarChart3,CalendarClock,Download,Plus } from "lucide-react";
import { initialCreatorReleases,type CreatorRelease,useLocalDemoState } from "@/lib/local-demo";
type Analytics={views:number;uniqueViewers:number;completionRate:number;averageWatchSeconds:number;topCountry:string;retention:number[]};
const demo:Analytics={views:128400,uniqueViewers:71200,completionRate:47,averageWatchSeconds:1122,topCountry:"JP",retention:[100,91,86,78,74,68,63,59,55,52,49,47]};
export function CreatorInsights(){
  const[releases,setReleases]=useLocalDemoState("aniverse.creator-releases",initialCreatorReleases);const[title,setTitle]=useState("");const[scheduledAt,setScheduledAt]=useState("");const[analytics,setAnalytics]=useState(demo);const[range,setRange]=useState("30d");
  useEffect(()=>{void fetch(`/api/v1/creator/analytics?range=${range}`).then(async(response)=>response.ok?response.json():Promise.reject()).then((data:{analytics:Analytics})=>setAnalytics(data.analytics)).catch(()=>undefined)},[range]);
  function exportAnalytics(){const rows=["segment,retention",...analytics.retention.map((value,index)=>`${index*2},${value}`)];const url=URL.createObjectURL(new Blob([rows.join("\n")],{type:"text/csv"}));const link=document.createElement("a");link.href=url;link.download="aniverse-creator-analytics.csv";link.click();URL.revokeObjectURL(url);}
  function schedule(event:React.FormEvent){event.preventDefault();if(!title||!scheduledAt)return;const release:CreatorRelease={id:crypto.randomUUID(),title,scheduledAt,kind:"Episode",status:"Scheduled"};setReleases((current)=>[release,...current]);setTitle("");setScheduledAt("");}
  const average=`${Math.floor(analytics.averageWatchSeconds/60)}m ${analytics.averageWatchSeconds%60}s`;
  return <><section id="analytics" className="studio-panel"><div className="panel-head"><div><p>AUDIENCE</p><h2>Creator analytics</h2></div><span className="analytics-actions"><select aria-label="Analytics range" value={range} onChange={(event)=>setRange(event.target.value)}><option value="7d">7 days</option><option value="30d">30 days</option><option value="90d">90 days</option></select><button onClick={exportAnalytics}><Download/>Export CSV</button></span></div><div className="analytics-metrics"><article><b>{analytics.views.toLocaleString()}</b><span>Views</span></article><article><b>{analytics.uniqueViewers.toLocaleString()}</b><span>Unique viewers</span></article><article><b>{analytics.completionRate}%</b><span>Completion</span></article><article><b>{average}</b><span>Average watch</span></article></div><div className="retention-chart" aria-label="Audience retention chart">{analytics.retention.map((value,index)=><i key={index} style={{height:`${value}%`}} title={`${index*2} min: ${value}%`}/>)}</div><p className="analytics-note"><BarChart3/>Top audience geography: {analytics.topCountry}. Only aggregate data is shown.</p></section><section id="releases" className="studio-panel"><div className="panel-head"><div><p>PUBLISHING CALENDAR</p><h2>Releases and premieres</h2></div><CalendarClock/></div><form className="release-form" onSubmit={schedule}><input aria-label="Release title" value={title} onChange={(event)=>setTitle(event.target.value)} placeholder="Episode, trailer, or announcement"/><input aria-label="Release time" type="datetime-local" value={scheduledAt} onChange={(event)=>setScheduledAt(event.target.value)}/><button><Plus/>Schedule</button></form><div className="release-list">{releases.map((release)=><article key={release.id}><div><b>{release.title}</b><span>{release.kind} · <time>{new Date(release.scheduledAt).toLocaleString()}</time></span></div><i>{release.status}</i></article>)}</div></section></>;
}
