"use client";

import { useCallback, useEffect, useState, type FormEvent } from "react";
import { CheckCircle2, LoaderCircle } from "lucide-react";
import { isSupabaseConfigured } from "@/lib/supabase/config";

type Request={id:string;titleName:string;status:string;submitted_at:string;work_description:string};
export function DmcaCounterCenter(){
  const cloud=isSupabaseConfigured();const[requests,setRequests]=useState<Request[]>([]);const[busy,setBusy]=useState(cloud);const[message,setMessage]=useState("");
  const load=useCallback(async()=>{if(!cloud)return;const response=await fetch("/api/v1/legal/dmca/counter",{cache:"no-store"});const data=await response.json().catch(()=>({}))as{requests?:Request[];error?:string};if(response.ok)setRequests(data.requests??[]);else setMessage(data.error??"Affected notices could not be loaded.");setBusy(false)},[cloud]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
  async function submit(event:FormEvent<HTMLFormElement>,requestId:string){event.preventDefault();const form=new FormData(event.currentTarget);setBusy(true);const response=await fetch("/api/v1/legal/dmca/counter",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({requestId,contactEmail:form.get("contactEmail"),statement:form.get("statement"),signature:form.get("signature"),goodFaithConfirmed:form.get("goodFaithConfirmed")==="on",jurisdictionConfirmed:form.get("jurisdictionConfirmed")==="on"})});const data=await response.json().catch(()=>({}))as{error?:string};setMessage(response.ok?"Your counter-notice was recorded for legal review.":data.error??"Counter-notice could not be recorded.");if(response.ok)await load();setBusy(false)}
  if(!cloud)return <div className="dmca-success"><CheckCircle2/><h2>Counter-notice center ready</h2><p>Sign in to a configured creator account to view copyright notices linked to your titles.</p></div>;
  return <div className="counter-center">{busy&&<LoaderCircle className="spin"/>}{message&&<p role="status">{message}</p>}{requests.map(request=><section key={request.id}><h2>{request.titleName}</h2><p>{request.work_description}</p><small>{request.status} · {new Date(request.submitted_at).toLocaleDateString()}</small><form className="dmca-form" onSubmit={event=>void submit(event,request.id)}><input required type="email" name="contactEmail" placeholder="Contact email"/><textarea required minLength={30} maxLength={5000} name="statement" placeholder="Explain why removal was a mistake or misidentification"/><input required minLength={2} maxLength={120} name="signature" placeholder="Electronic signature"/><label className="dmca-check"><input required name="goodFaithConfirmed" type="checkbox"/>I have a good-faith belief that removal resulted from mistake or misidentification.</label><label className="dmca-check"><input required name="jurisdictionConfirmed" type="checkbox"/>I consent to the applicable court jurisdiction and accept service from the claimant.</label><button disabled={busy}>Submit counter-notice</button></form></section>)}{!busy&&!requests.length&&<p>No eligible copyright notices are linked to your creator titles.</p>}</div>
}
