"use client";

import { useCallback, useEffect, useState } from "react";
import { FileWarning, Gavel, LoaderCircle } from "lucide-react";
import { isSupabaseConfigured } from "@/lib/supabase/config";

type Title = { id: string; name: string; status: string };
type Request = { id:string; claimant_name:string; claimant_email:string; work_description:string; material_urls:string[]; status:string; submitted_at:string; title_id:string|null; review_notes:string|null };
type Counter = { id:string; request_id:string; statement:string; status:string };
const demoRequests:Request[]=[{id:"24fd8712-e874-4fde-820b-9c9dff9ce6f1",claimant_name:"Northstar Rights",claimant_email:"legal@northstar.example",work_description:"Copyright ownership claim for episode footage.",material_urls:["https://aniverse.example/watch/neon-horizon-1"],status:"submitted",submitted_at:"2026-07-29T18:00:00Z",title_id:null,review_notes:null}];
const demoTitles:Title[]=[{id:"ffb87e7e-e2d4-46c0-8e50-fbb5d781fe72",name:"Neon Horizon",status:"published"}];

export function DmcaOperations(){
  const cloud=isSupabaseConfigured();const[requests,setRequests]=useState<Request[]>(cloud?[]:demoRequests);const[counters,setCounters]=useState<Counter[]>([]);const[titles,setTitles]=useState<Title[]>(cloud?[]:demoTitles);const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");
  const load=useCallback(async()=>{if(!cloud)return;setBusy(true);const response=await fetch("/api/v1/admin/dmca",{cache:"no-store"});const data=await response.json().catch(()=>({}))as{requests?:Request[];counterNotices?:Counter[];titles?:Title[];error?:string};if(response.ok){setRequests(data.requests??[]);setCounters(data.counterNotices??[]);setTitles(data.titles??[])}else setMessage(data.error??"DMCA queue could not be loaded.");setBusy(false)},[cloud]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
  async function act(payload:object){if(!cloud){setMessage("Demo action recorded locally.");return}setBusy(true);const response=await fetch("/api/v1/admin/dmca",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const data=await response.json().catch(()=>({}))as{error?:string};setMessage(response.ok?"DMCA decision recorded.":data.error??"Decision failed.");if(response.ok)await load();setBusy(false)}
  return <section className="moderation-panel dmca-operations"><div className="panel-title"><div><p>COPYRIGHT OPERATIONS</p><h2>DMCA review queue</h2></div>{busy?<LoaderCircle className="spin"/>:<Gavel/>}</div>{message&&<p role="status">{message}</p>}<div className="dmca-admin-grid"><div>{requests.map(item=><article key={item.id}><header><span><FileWarning/></span><div><b>{item.claimant_name}</b><small>{item.claimant_email}</small></div><i>{item.status}</i></header><p>{item.work_description}</p><a href={item.material_urls[0]} target="_blank" rel="noreferrer">Review reported material</a><form onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);void act({action:"review",id:item.id,decision:"reviewing",titleId:form.get("titleId")||null,notes:form.get("notes")})}}><select name="titleId" defaultValue={item.title_id??""} aria-label="Affected title"><option value="">Link affected title</option>{titles.map(title=><option value={title.id} key={title.id}>{title.name}</option>)}</select><input name="notes" minLength={10} required placeholder="Document review evidence"/><button disabled={busy}>Start review</button><button disabled={busy} type="button" onClick={event=>{const form=event.currentTarget.form;if(!form?.reportValidity())return;const data=new FormData(form);void act({action:"execute",id:item.id,notes:data.get("notes")})}}>Execute takedown</button><button disabled={busy} type="button" onClick={event=>{const form=event.currentTarget.form;if(!form?.reportValidity())return;const data=new FormData(form);void act({action:"review",id:item.id,decision:"rejected",titleId:data.get("titleId")||null,notes:data.get("notes")})}}>Reject</button></form></article>)}{!requests.length&&<p>No copyright notices require review.</p>}</div><aside><h3>Counter-notices</h3>{counters.map(counter=><article key={counter.id}><b>{counter.status}</b><p>{counter.statement}</p><button onClick={()=>void act({action:"counter",id:counter.id,decision:"reviewing",notes:"Counter-notice assigned for legal review."})}>Assign review</button></article>)}{!counters.length&&<p>No counter-notices are waiting.</p>}</aside></div></section>
}
