"use client";

import { useCallback, useEffect, useState, type FormEvent } from "react";
import { LifeBuoy, LoaderCircle, Radio, Send } from "lucide-react";
import { isSupabaseConfigured } from "@/lib/supabase/config";

type Ticket={id:string;requester:string;subject:string;category:string;status:string;priority:string;support_ticket_messages:Array<{id:number;body:string;staff_note:boolean;created_at:string}>};
type Incident={id:string;title:string;body:string;severity:string;status:string;affected_services:string[];published:boolean};
export function SupportOperations(){
  const[tickets,setTickets]=useState<Ticket[]>([]);const[incidents,setIncidents]=useState<Incident[]>([]);const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");const cloud=isSupabaseConfigured();
  const load=useCallback(async()=>{if(!cloud)return;setBusy(true);const response=await fetch("/api/v1/admin/support",{cache:"no-store"});const data=await response.json().catch(()=>({}))as{tickets?:Ticket[];incidents?:Incident[];error?:string};if(response.ok){setTickets(data.tickets??[]);setIncidents(data.incidents??[])}else setMessage(data.error??"Support operations could not be loaded.");setBusy(false)},[cloud]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
  async function action(payload:object){setBusy(true);const response=await fetch("/api/v1/admin/support",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});setMessage(response.ok?"Support operation saved.":"Support operation could not be saved.");if(response.ok)await load();setBusy(false)}
  async function incident(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await action({action:"incident",title:form.get("title"),body:form.get("body"),severity:form.get("severity"),status:form.get("status"),affectedServices:String(form.get("services")).split(",").map(item=>item.trim()).filter(Boolean),published:form.get("published")==="on"});event.currentTarget.reset()}
  if(!cloud)return null;
  return <section className="moderation-panel support-operations"><div className="panel-title"><div><p>MEMBER CARE</p><h2>Support and status operations</h2></div>{busy?<LoaderCircle className="spin"/>:<LifeBuoy/>}</div>{message&&<p role="status">{message}</p>}<div className="support-admin-grid"><div><h3>Ticket queue</h3>{tickets.map(ticket=><article key={ticket.id}><header><div><b>{ticket.subject}</b><small>{ticket.requester} · {ticket.category}</small></div><i>{ticket.priority} · {ticket.status}</i></header>{ticket.support_ticket_messages.map(item=><p className={item.staff_note?"internal":""} key={item.id}>{item.body}</p>)}<form onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);void action({action:"reply",ticketId:ticket.id,message:form.get("message"),internal:form.get("internal")==="on"});event.currentTarget.reset()}}><input required name="message" aria-label={`Reply to ${ticket.subject}`}/><label><input type="checkbox" name="internal"/>Internal</label><button><Send/></button></form><div className="ticket-actions"><button onClick={()=>void action({action:"status",ticketId:ticket.id,status:"in_progress",priority:ticket.priority})}>Claim</button><button onClick={()=>void action({action:"status",ticketId:ticket.id,status:"resolved",priority:ticket.priority})}>Resolve</button></div></article>)}</div><div><h3><Radio/>Publish incident</h3><form className="incident-form" onSubmit={incident}><input required minLength={5} maxLength={160} name="title" placeholder="Incident title"/><textarea required minLength={10} maxLength={5000} name="body" placeholder="Public update"/><input name="services" placeholder="Playback, Authentication"/><div><select name="severity"><option>maintenance</option><option>minor</option><option>major</option><option>critical</option></select><select name="status"><option>investigating</option><option>identified</option><option>monitoring</option><option>resolved</option></select></div><label><input type="checkbox" name="published"/>Publish publicly</label><button>Save incident</button></form><div className="incident-summary">{incidents.map(item=><p key={item.id}><b>{item.title}</b><span>{item.status} · {item.published?"public":"draft"}</span></p>)}</div></div></div></section>
}
