"use client";
import { useEffect, useState } from "react";
import { Ban,Download,Eye,FileUp,LoaderCircle,LogOut,Shield,Trash2 } from "lucide-react";
import { deleteAllLocalData,exportLocalData,importLocalData } from "@/lib/local-data/database";
import { useLocalDemoState } from "@/lib/local-demo";
import { isSupabaseConfigured } from "@/lib/supabase/config";
type Privacy={profile:"public"|"followers"|"private";showActivity:boolean;personalization:boolean;analytics:boolean;blocked:string[]};
const initialPrivacy:Privacy={profile:"public",showActivity:true,personalization:true,analytics:true,blocked:["spam-universe"]};
export function AccountControls(){
  const [privacy,setPrivacy]=useLocalDemoState("aniverse.privacy",initialPrivacy);const [message,setMessage]=useState("");const[sessions,setSessions]=useState<Array<{id:string;device_name:string;last_seen_at:string;current:boolean}>>([]);const[busy,setBusy]=useState(false);const cloud=isSupabaseConfigured();
  useEffect(()=>{const timer=setTimeout(()=>{void fetch("/api/v1/preferences").then(async(response)=>response.ok?response.json():Promise.reject()).then((data:{preferences:{personalizationEnabled:boolean;playbackAnalyticsEnabled:boolean}})=>setPrivacy((current)=>({...current,personalization:data.preferences.personalizationEnabled,analytics:data.preferences.playbackAnalyticsEnabled}))).catch(()=>undefined);if(cloud){const deviceName=`${navigator.platform||"Browser"} · ${navigator.userAgent.includes("Mobile")?"Mobile":"Web"}`;void fetch("/api/v1/account/sessions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({deviceName})}).then(()=>fetch("/api/v1/account/sessions",{cache:"no-store"})).then(response=>response.ok?response.json():Promise.reject()).then((data:{sessions:typeof sessions})=>setSessions(data.sessions)).catch(()=>setMessage("Sessions are temporarily unavailable."))}},0);return()=>clearTimeout(timer)},[cloud,setPrivacy]);
  async function savePreference(next:Privacy,key:"personalizationEnabled"|"playbackAnalyticsEnabled",value:boolean){setPrivacy(next);const response=await fetch("/api/v1/preferences",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({[key]:value})});if(response.ok)setMessage("Privacy preference saved.");}
  async function download(){const backup=await exportLocalData();const payload={...backup,localStorage:Object.fromEntries(Object.keys(localStorage).filter((key)=>key.startsWith("aniverse.")).map((key)=>[key,localStorage.getItem(key)]))};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}));const link=document.createElement("a");link.href=url;link.download=`aniverse-backup-${new Date().toISOString().slice(0,10)}.json`;link.click();URL.revokeObjectURL(url);setMessage("Account export created.");}
  async function restore(file:File){const backup=JSON.parse(await file.text());await importLocalData(backup);for(const [key,value]of Object.entries(backup.localStorage??{}))if(typeof value==="string")localStorage.setItem(key,value);setMessage("Backup restored. Reload to see every change.");}
  async function removeAccount(){if(!confirm("Delete all AniVerse data stored in this browser?"))return;await deleteAllLocalData();Object.keys(localStorage).filter((key)=>key.startsWith("aniverse.")).forEach((key)=>localStorage.removeItem(key));location.assign("/");}
  async function revokeOthers(){setBusy(true);const response=await fetch("/api/v1/account/sessions",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({scope:"others"})});if(response.ok){setSessions(current=>current.filter(item=>item.current));setMessage("Other sessions signed out.")}else setMessage("Other sessions could not be signed out.");setBusy(false)}
  return <section className="account-controls"><header><p>PRIVACY & DATA</p><h2>Control your AniVerse account</h2></header><div className="privacy-grid">
    <label><Eye/>Profile visibility<select value={privacy.profile} onChange={(event)=>setPrivacy({...privacy,profile:event.target.value as Privacy["profile"]})}><option value="public">Public</option><option value="followers">Followers</option><option value="private">Private</option></select></label>
    <label><input type="checkbox" checked={privacy.showActivity} onChange={(event)=>setPrivacy({...privacy,showActivity:event.target.checked})}/><Shield/>Show activity feed</label>
    <label><input type="checkbox" checked={privacy.personalization} onChange={(event)=>void savePreference({...privacy,personalization:event.target.checked},"personalizationEnabled",event.target.checked)}/><Shield/>Personalized recommendations</label>
    <label><input type="checkbox" checked={privacy.analytics??true} onChange={(event)=>void savePreference({...privacy,analytics:event.target.checked},"playbackAnalyticsEnabled",event.target.checked)}/><Shield/>Share playback analytics</label>
  </div><div className="blocked-users"><Ban/><div><b>Blocked accounts</b><span>{privacy.blocked.join(", ")||"None"}</span></div><button onClick={()=>setPrivacy({...privacy,blocked:[]})}>Clear</button></div><div className="session-list"><h3>Sessions</h3>{cloud?sessions.map(item=><article key={item.id}><div><b>{item.device_name}</b><span>{item.current?"This session · ":""}{new Date(item.last_seen_at).toLocaleString()}</span></div>{item.current&&<i>Current</i>}</article>):<article><div><b>This browser</b><span>Local mode · Active now</span></div></article>}{cloud&&sessions.some(item=>!item.current)&&<button disabled={busy} onClick={()=>void revokeOthers()}>{busy?<LoaderCircle className="spin"/>:<LogOut/>}Sign out other devices</button>}</div><div className="data-actions"><button onClick={()=>void download()}><Download/>Export data</button><label><FileUp/>Restore backup<input type="file" accept="application/json" onChange={(event)=>{const file=event.target.files?.[0];if(file)void restore(file);}}/></label><button className="danger" onClick={()=>void removeAccount()}><Trash2/>Delete account data</button></div>{message&&<p role="status">{message}</p>}</section>;
}
