import { randomUUID } from "node:crypto";
import { decryptBackup,encryptBackup } from "@/lib/account-backup";
import { consumeRateLimit } from "@/lib/security";
import { getAdminClient } from "@/lib/supabase/admin";
import { createClient } from "@/lib/supabase/server";

const bucket="account-backups";
async function identity(){const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();return{supabase,user}}
export async function GET(request:Request){const{supabase,user}=await identity();if(!user)return Response.json({error:"Authentication required"},{status:401});const id=new URL(request.url).searchParams.get("id");if(!id){const{data,error}=await supabase.from("cloud_backups").select("id,byte_size,checksum,created_at").eq("user_id",user.id).order("created_at",{ascending:false}).limit(5);return error?Response.json({error:"Could not list backups"},{status:500}):Response.json({backups:data})}const{data:record}=await supabase.from("cloud_backups").select("object_path,checksum").eq("id",id).eq("user_id",user.id).maybeSingle();if(!record)return Response.json({error:"Backup not found"},{status:404});const{data,error}=await getAdminClient().storage.from(bucket).download(record.object_path);if(error||!data)return Response.json({error:"Backup object is unavailable"},{status:404});try{return Response.json({payload:decryptBackup(new Uint8Array(await data.arrayBuffer()),record.checksum)},{headers:{"cache-control":"private, no-store"}})}catch{return Response.json({error:"Backup integrity check failed"},{status:422})}}
export async function POST(request:Request){const origin=request.headers.get("origin");if(origin&&origin!==new URL(request.url).origin)return Response.json({error:"Untrusted backup origin"},{status:403});const{supabase,user}=await identity();if(!user)return Response.json({error:"Authentication required"},{status:401});if(!consumeRateLimit(`backup:${user.id}`,3,1/300))return Response.json({error:"Too many backup attempts"},{status:429});if(Number(request.headers.get("content-length")??0)>5_242_880)return Response.json({error:"Backup is too large"},{status:413});const body=await request.json().catch(()=>null) as {payload?:unknown}|null;if(!body||body.payload===undefined)return Response.json({error:"Backup payload is required"},{status:400});const{bytes,checksum}=encryptBackup(body.payload);if(bytes.length>10_485_760)return Response.json({error:"Encrypted backup is too large"},{status:413});const objectPath=`${user.id}/${Date.now()}-${randomUUID()}.backup`;const admin=getAdminClient();const{error:uploadError}=await admin.storage.from(bucket).upload(objectPath,bytes,{contentType:"application/octet-stream",upsert:false});if(uploadError)return Response.json({error:"Could not store backup"},{status:502});const{data:record,error:insertError}=await supabase.from("cloud_backups").insert({user_id:user.id,object_path:objectPath,byte_size:bytes.length,checksum}).select("id,byte_size,created_at").single();if(insertError){await admin.storage.from(bucket).remove([objectPath]);return Response.json({error:"Could not record backup"},{status:500})}const{data:stale}=await supabase.from("cloud_backups").select("id,object_path").eq("user_id",user.id).order("created_at",{ascending:false}).range(5,50);if(stale?.length){await admin.storage.from(bucket).remove(stale.map(item=>item.object_path));await supabase.from("cloud_backups").delete().eq("user_id",user.id).in("id",stale.map(item=>item.id))}return Response.json({backup:record},{status:201})}
export async function DELETE(request:Request){const origin=request.headers.get("origin");if(origin&&origin!==new URL(request.url).origin)return Response.json({error:"Untrusted backup origin"},{status:403});const{supabase,user}=await identity();if(!user)return Response.json({error:"Authentication required"},{status:401});const id=new URL(request.url).searchParams.get("id");if(!id)return Response.json({error:"Backup id is required"},{status:400});const{data:record}=await supabase.from("cloud_backups").select("object_path").eq("id",id).eq("user_id",user.id).maybeSingle();if(!record)return Response.json({error:"Backup not found"},{status:404});const{error}=await getAdminClient().storage.from(bucket).remove([record.object_path]);if(error)return Response.json({error:"Could not delete backup object"},{status:502});await supabase.from("cloud_backups").delete().eq("id",id).eq("user_id",user.id);return new Response(null,{status:204})}
