import { z } from "zod";
import { creatorSlug } from "@/lib/creator-applications";
import { getAdminClient } from "@/lib/supabase/admin";
import { isSupabaseConfigured } from "@/lib/supabase/config";
import { createClient } from "@/lib/supabase/server";
const reviewSchema=z.object({id:z.uuid(),decision:z.enum(["approved","rejected"]),notes:z.string().trim().max(1000).default("")});
async function administrator(){if(!isSupabaseConfigured()||!process.env.SUPABASE_SERVICE_ROLE_KEY)return null;const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)return null;const{data:role}=await supabase.from("user_roles").select("role").eq("user_id",user.id).eq("role","admin").maybeSingle();return role?user:null;}
export async function GET(){const reviewer=await administrator();if(!reviewer)return Response.json({error:"Administrator access required"},{status:403});const admin=getAdminClient();const{data,error}=await admin.from("creator_applications").select("id,user_id,channel_name,legal_name,portfolio_url,rights_summary,status,submitted_at,reviewed_at,review_notes").in("status",["submitted","approved","rejected"]).order("submitted_at",{ascending:false});if(error)return Response.json({error:"Could not load creator queue"},{status:500});const ids=(data??[]).map((item)=>item.user_id);const{data:profiles}=ids.length?await admin.from("profiles").select("id,display_name").in("id",ids):{data:[]};const names=new Map((profiles??[]).map((profile)=>[profile.id,profile.display_name]));return Response.json({applications:(data??[]).map((item)=>({...item,applicant_name:names.get(item.user_id)??"Applicant"}))},{headers:{"cache-control":"private, no-store"}})}
export async function PATCH(request:Request){const reviewer=await administrator();if(!reviewer)return Response.json({error:"Administrator access required"},{status:403});const parsed=reviewSchema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return Response.json({error:"Invalid review decision"},{status:400});const admin=getAdminClient();const{data:application}=await admin.from("creator_applications").select("id,user_id,channel_name,status").eq("id",parsed.data.id).maybeSingle();if(!application)return Response.json({error:"Application not found"},{status:404});if(application.status!=="submitted")return Response.json({error:"Application has already been reviewed"},{status:409});const now=new Date().toISOString();if(parsed.data.decision==="approved"){let{data:team}=await admin.from("creator_teams").select("id").eq("created_by",application.user_id).limit(1).maybeSingle();let createdTeamId:string|undefined;if(!team){const result=await admin.from("creator_teams").insert({name:application.channel_name,slug:creatorSlug(application.channel_name,application.id),created_by:application.user_id}).select("id").single();if(result.error)return Response.json({error:"Could not provision creator team"},{status:500});team=result.data;createdTeamId=team.id}const{error:membershipError}=await admin.from("creator_team_memberships").upsert({team_id:team.id,user_id:application.user_id,role:"owner",invited_by:reviewer.id});if(membershipError){if(createdTeamId)await admin.from("creator_teams").delete().eq("id",createdTeamId);return Response.json({error:"Could not provision team membership"},{status:500})}const{error:roleError}=await admin.from("user_roles").upsert({user_id:application.user_id,role:"creator",granted_by:reviewer.id});if(roleError)return Response.json({error:"Could not grant creator role"},{status:500})}const{data,error}=await admin.from("creator_applications").update({status:parsed.data.decision,reviewed_at:now,reviewed_by:reviewer.id,review_notes:parsed.data.notes||null,updated_at:now}).eq("id",application.id).eq("status","submitted").select("id,status,reviewed_at").single();if(error)return Response.json({error:"Could not save review decision"},{status:500});await admin.from("audit_logs").insert({actor_id:reviewer.id,action:`creator_application.${parsed.data.decision}`,entity_type:"creator_application",entity_id:application.id,metadata:{applicant_id:application.user_id}});return Response.json({application:data})}
