create table public.watch_parties (
  id uuid primary key default gen_random_uuid(), host_id uuid not null references public.profiles(id) on delete cascade,
  title_id uuid references public.titles(id) on delete cascade, episode_id uuid references public.episodes(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 120), status text not null default 'scheduled' check (status in ('scheduled','live','ended')),
  playback_position integer not null default 0 check (playback_position >= 0), playback_state text not null default 'paused' check (playback_state in ('playing','paused')),
  sequence bigint not null default 0, starts_at timestamptz, created_at timestamptz not null default now()
);
create table public.watch_party_members (party_id uuid references public.watch_parties(id) on delete cascade, user_id uuid references public.profiles(id) on delete cascade, role text not null default 'viewer' check(role in ('host','moderator','viewer')), joined_at timestamptz not null default now(), primary key(party_id,user_id));
create table public.watch_party_messages (id uuid primary key default gen_random_uuid(), party_id uuid not null references public.watch_parties(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, body text not null check(char_length(body) between 1 and 1000), created_at timestamptz not null default now());
create table public.push_subscriptions (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, endpoint text not null unique, p256dh text not null, auth text not null, user_agent text, created_at timestamptz not null default now());
create table public.user_sessions (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, auth_session_id uuid, device_name text not null, last_seen_at timestamptz not null default now(), revoked_at timestamptz);
create table public.cloud_backups (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, object_path text not null unique, byte_size bigint not null check(byte_size>=0), checksum text not null, created_at timestamptz not null default now());
create table public.playback_events (id bigint generated always as identity primary key, user_id uuid references public.profiles(id) on delete set null, title_id uuid not null references public.titles(id) on delete cascade, episode_id uuid references public.episodes(id) on delete set null, event_type text not null check(event_type in ('start','progress','seek','complete')), position_seconds integer not null default 0, duration_seconds integer not null default 0, country_code text check(country_code ~ '^[A-Z]{2}$'), occurred_at timestamptz not null default now());

create index watch_party_members_user_idx on public.watch_party_members(user_id,party_id);create index watch_party_messages_party_idx on public.watch_party_messages(party_id,created_at);create index push_subscriptions_user_idx on public.push_subscriptions(user_id);create index user_sessions_user_idx on public.user_sessions(user_id,last_seen_at desc);create index cloud_backups_user_idx on public.cloud_backups(user_id,created_at desc);create index playback_events_title_time_idx on public.playback_events(title_id,occurred_at desc);create index playback_events_user_idx on public.playback_events(user_id,occurred_at desc);

alter table public.watch_parties enable row level security;alter table public.watch_party_members enable row level security;alter table public.watch_party_messages enable row level security;alter table public.push_subscriptions enable row level security;alter table public.user_sessions enable row level security;alter table public.cloud_backups enable row level security;alter table public.playback_events enable row level security;
grant select,insert,update,delete on public.watch_parties,public.watch_party_members,public.watch_party_messages,public.push_subscriptions,public.user_sessions,public.cloud_backups to authenticated;grant insert,select on public.playback_events to authenticated;grant usage,select on sequence public.playback_events_id_seq to authenticated;

create policy "members read parties" on public.watch_parties for select to authenticated using(host_id=(select auth.uid()) or exists(select 1 from public.watch_party_members m where m.party_id=id and m.user_id=(select auth.uid())));create policy "hosts create parties" on public.watch_parties for insert to authenticated with check(host_id=(select auth.uid()));create policy "hosts update parties" on public.watch_parties for update to authenticated using(host_id=(select auth.uid())) with check(host_id=(select auth.uid()));create policy "hosts delete parties" on public.watch_parties for delete to authenticated using(host_id=(select auth.uid()));
create policy "members read memberships" on public.watch_party_members for select to authenticated using(user_id=(select auth.uid()) or exists(select 1 from public.watch_parties p where p.id=party_id and p.host_id=(select auth.uid())));create policy "users join parties" on public.watch_party_members for insert to authenticated with check(user_id=(select auth.uid()));create policy "users leave parties" on public.watch_party_members for delete to authenticated using(user_id=(select auth.uid()) or exists(select 1 from public.watch_parties p where p.id=party_id and p.host_id=(select auth.uid())));
create policy "members read messages" on public.watch_party_messages for select to authenticated using(exists(select 1 from public.watch_party_members m where m.party_id=watch_party_messages.party_id and m.user_id=(select auth.uid())));create policy "members send messages" on public.watch_party_messages for insert to authenticated with check(user_id=(select auth.uid()) and exists(select 1 from public.watch_party_members m where m.party_id=watch_party_messages.party_id and m.user_id=(select auth.uid())));
create policy "users manage push subscriptions" on public.push_subscriptions for all to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));create policy "users manage sessions" on public.user_sessions for all to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));create policy "users manage backups" on public.cloud_backups for all to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));create policy "users insert playback events" on public.playback_events for insert to authenticated with check(user_id=(select auth.uid()));create policy "users read playback events" on public.playback_events for select to authenticated using(user_id=(select auth.uid()));

create policy "party members receive realtime" on realtime.messages for select to authenticated using((select realtime.topic()) like 'party:%' and exists(select 1 from public.watch_party_members m where m.user_id=(select auth.uid()) and 'party:'||m.party_id::text=(select realtime.topic())));create policy "party members send realtime" on realtime.messages for insert to authenticated with check((select realtime.topic()) like 'party:%' and exists(select 1 from public.watch_party_members m where m.user_id=(select auth.uid()) and 'party:'||m.party_id::text=(select realtime.topic())));
